CREATE DATABASE University

CREATE TABLE Majors
(
	MajorID INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50)
)

CREATE TABLE Students
(
	StudentID INT IDENTITY PRIMARY KEY NOT NULL,
	StudentNumber VARCHAR(20) UNIQUE,
	StudentName VARCHAR(50),
	MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
	PaymentID INT IDENTITY PRIMARY KEY NOT NULL,
	PaymentDate DATETIME2 ,
	PaymentAmount DECIMAL(8, 2),
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE [Subject]
(
	SubjectID INT IDENTITY PRIMARY KEY NOT NULL,
	SubjectName VARCHAR(50)
)

CREATE TABLE Agenda
(
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID) NOT NULL,
	SubjectID INT FOREIGN KEY REFERENCES [Subject](SubjectID) NOT NULL,
	PRIMARY KEY (StudentID, SubjectID)
)

